## PANDAS

In [4]:
# Importamos librerias
import numpy as np
import pandas as pd

In [5]:
# Creamos una Serie -> Una 
zanahoria = pd.Series(data=[1,2,4.5,6,7], 
                      index = ['primero','segundo','tercero','cuarto','quinto'])

zanahoria

primero    1.0
segundo    2.0
tercero    4.5
cuarto     6.0
quinto     7.0
dtype: float64

In [6]:
print(f"Zanahoria es del tipo {type(zanahoria)}")
print(f"Accediendo al elemento 3 de la serie: {zanahoria['tercero']}")

Zanahoria es del tipo <class 'pandas.Series'>
Accediendo al elemento 3 de la serie: 4.5

In [20]:
# Creamos un DataFrame

espejo = pd.DataFrame(data=[1,'rosa',3,4,6.7,-10], 
                  index=['primero','segundo','tercero','cuarto','quinto','sexto'])
espejo

            0
primero     1
segundo  rosa
tercero     3
cuarto      4
quinto    6.7
sexto     -10

In [21]:
print(f"espejo es del tipo {type(espejo)}")

# Con el metodo index, vemos todos los indices que posee nuestro dataframe
print(f"Indices de nuestro DataFrame:\n{espejo.index}")

# Con el metodo columns, vemos todos las columnas que posee nuestro dataframe
print(f"Columnas de nuestro DataFrame:\n{espejo.columns}")

espejo es del tipo <class 'pandas.DataFrame'>
Indices de nuestro DataFrame:
Index(['primero', 'segundo', 'tercero', 'cuarto', 'quinto', 'sexto'], dtype='str')
Columnas de nuestro DataFrame:
RangeIndex(start=0, stop=1, step=1)

In [23]:
"""Pandas nos facilita con varias funciones para leer archivos. Entre ellas podemos encontrar:
- .read_csv(): lee archivos `csv` como DataFrame
- .read_json(): lee archivos `json` como DataFrame
- .read_excel(): leer archivos `excel` como DataFrame
"""

#Leemos el .csv 'StudensPerformance

students_df = pd.read_csv('StudentsPerformance.csv',
                          delimiter=',')
students_df

,Unnamed: 0,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,7.2,72,74
1,1,female,group C,some college,standard,completed,6.9,90,88
2,2,female,group B,master's degree,standard,none,9.0,95,93
3,3,male,group A,associate's degree,free/reduced,none,4.7,57,44
4,4,male,group C,some college,standard,none,7.6,78,75
...,...,...,...,...,...,...,...,...,...
995,995,female,group E,master's degree,standard,completed,8.8,99,95
996,996,male,group C,high school,free/reduced,none,6.2,55,55
997,997,female,group C,high school,free/reduced,completed,5.9,71,65
998,998,female,group D,some college,standard,completed,6.8,78,77
999,999,female,group D,some college,free/reduced,none,7.7,86,86

In [ ]:
# df.index -> Chequeo cuantos son sus indices
print(f"Indices del dataframe 'students_df: {students_df.index}")

# df.columns -> Chequeo cuales son sus columnas
print(f"Columnas del dataframe 'students_df:\n{students_df.columns}")

Indices del dataframe 'students_df: RangeIndex(start=0, stop=1000, step=1)
Columnas del dataframe 'students_df:
Index(['Unnamed: 0', 'gender', 'race/ethnicity', 'parental level of education',
       'lunch', 'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')

In [30]:
# Chequeo que estructura de datos es
print(f"La estructura de datos es de tipo: {type(students_df)}")

La estructura de datos es de tipo: <class 'pandas.DataFrame'>

In [ ]:
# df.shape -> Devuelve el numero de filas y columnas respectivamente.

print(f"¿Cuantas filas y columnas tiene `students`? -> {students_df.shape}")

¿Cuantas filas y columnas tiene `students`? -> (1000, 9)

In [ ]:
# df.head() -> Inspecciona las 5 primeras filas del dataframe.

print(f"Inspeccionamos las primeras 5 filas:\n{students_df.head()}")

Inspeccionamos las primeras 10 filas:
   Unnamed: 0  gender race/ethnicity parental level of education  \
0           0  female        group B           bachelor's degree
1           1  female        group C                some college
2           2  female        group B             master's degree
3           3    male        group A          associate's degree
4           4    male        group C                some college

          lunch test preparation course  math score  reading score  \
0      standard                    none         7.2             72
1      standard               completed         6.9             90
2      standard                    none         9.0             95
3  free/reduced                    none         4.7             57
4      standard                    none         7.6             78

   writing score
0             74
1             88
2             93
3             44
4             75

In [34]:
# df.tail() -> Inspecciona las 5 ultimas filas del dataframe.

print(f"Inspeccionamos las ultimas 5 filas:\n{students_df.tail()}")

Inspeccionamos las ultimas 5 filas:
     Unnamed: 0  gender race/ethnicity parental level of education  \
995         995  female        group E             master's degree
996         996    male        group C                 high school
997         997  female        group C                 high school
998         998  female        group D                some college
999         999  female        group D                some college

            lunch test preparation course  math score  reading score  \
995      standard               completed         8.8             99
996  free/reduced                    none         6.2             55
997  free/reduced               completed         5.9             71
998      standard               completed         6.8             78
999  free/reduced                    none         7.7             86

     writing score
995             95
996             55
997             65
998             77
999             86

In [36]:
# df.dtypes -> Devuelve el tipo de datos de cada una de las columnas de nuestro dataframe.

print(f"¿Que tipos de datos contiene cada una de las columnas de `students`?:\n{students_df.dtypes}")

¿Que tipos de datos contiene cada una de las columnas de `students`?:
Unnamed: 0                       int64
gender                             str
race/ethnicity                     str
parental level of education        str
lunch                              str
test preparation course            str
math score                     float64
reading score                    int64
writing score                    int64
dtype: object

In [ ]:
# Para acceder a una columna de nuestro dataframe debemos: df['nombre_columna]
print(f"Accedemos a la columna 'gender' del DataFrame:\n{students_df['gender']}")

# Otra forma de acceder a una columna es:
students_df.gender

Accedemos a la columna 'gender' del DataFrame:
0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: str

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: str

In [ ]:
# Otra forma de acceder es usando las funciones: loc[] e iloc[]
# iloc[1:m, 1:n] -> Se usa para seleccionar filas basadas en su posición de 1 a m filas y de 1 a n columnas.

students_df.iloc[:2,:3] # Aqui estoy accediendo a las 2 primeras filas y a las 3 primeras columnas.

   Unnamed: 0  gender race/ethnicity
0           0  female        group B
1           1  female        group C

In [42]:
# Traer las primeras 5 filas de todas las columnas
students_df.iloc[:5]

,Unnamed: 0,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,7.2,72,74
1,1,female,group C,some college,standard,completed,6.9,90,88
2,2,female,group B,master's degree,standard,none,9.0,95,93
3,3,male,group A,associate's degree,free/reduced,none,4.7,57,44
4,4,male,group C,some college,standard,none,7.6,78,75

In [ ]:
# Traer las ultimas 5 filas de todas las columnas
students_df.iloc[-5:]

,Unnamed: 0,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,995,female,group E,master's degree,standard,completed,8.8,99,95
996,996,male,group C,high school,free/reduced,none,6.2,55,55
997,997,female,group C,high school,free/reduced,completed,5.9,71,65
998,998,female,group D,some college,standard,completed,6.8,78,77
999,999,female,group D,some college,free/reduced,none,7.7,86,86

In [48]:
# Taer todas las filas de las 2 ultimas columnas
students_df.iloc[:,-2:]

     reading score  writing score
0               72             74
1               90             88
2               95             93
3               57             44
4               78             75
..             ...            ...
995             99             95
996             55             55
997             71             65
998             78             77
999             86             86

[1000 rows x 2 columns]

In [49]:
# Taer los datos entre la decima y vigecima fila
students_df.iloc[10:21]

,Unnamed: 0,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
10,10,male,group C,associate's degree,standard,none,5.8,54,52
11,11,male,group D,associate's degree,standard,none,4.0,52,43
12,12,female,group B,high school,standard,none,6.5,81,73
13,13,male,group A,some college,standard,completed,7.8,72,70
14,14,female,group A,master's degree,standard,none,5.0,53,58
15,15,female,group C,some high school,standard,none,6.9,75,78
16,16,male,group C,high school,standard,none,8.8,89,86
17,17,female,group B,some high school,free/reduced,none,1.8,32,28
18,18,male,group C,master's degree,free/reduced,completed,4.6,42,46
19,19,female,group C,associate's degree,free/reduced,none,5.4,58,61
20,20,male,group D,high school,standard,none,6.6,69,63

In [50]:
#.loc[[nombre_fila], [nombre_columna]] -> Se usa para seleccionar filas o columnas basadas en su nombre

# Trae los datos cuyo indice sea igual a 1.
students_df.loc[1]

Unnamed: 0                                1
gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course           completed
math score                              6.9
reading score                            90
writing score                            88
Name: 1, dtype: object

In [ ]:
# Trae las filas 1,20,3,4,5 de las columnas 'gender' y 'lucnh'
students_df.loc[[1,20,3,4,5],['gender','lunch']]

    gender         lunch
1   female      standard
20    male      standard
3     male  free/reduced
4     male      standard
5   female      standard

In [52]:
# Traer las filas con indices 3, 10, 30, 43, 43 y columnas reading score y writing score
students_df.loc[[3,10,30,43],['reading score','writing score']]

    reading score  writing score
3              57             44
10             54             52
30             74             74
43             65             66

## MASCARAS BOOLEANAS

In [55]:
# df['col1'] > 10     --> Esto es una mascara booleana ya que devuelve valores booleanos.
# df[df['col1] > 10]  --> Solo trae datos de aquellas filas que cumplas con las mascara booleana.

# Traer solo las filas donde 'math score' sea mayor a 7.0
students_df['math score'] > 7.0 # Esta es la MASCARA BOOLEANA

students_df[students_df['math score'] > 7.0] # Filtramos los datos que cumplen las condicion

,Unnamed: 0,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,7.2,72,74
2,2,female,group B,master's degree,standard,none,9.0,95,93
4,4,male,group C,some college,standard,none,7.6,78,75
5,5,female,group B,associate's degree,standard,none,7.1,83,78
6,6,female,group B,some college,standard,completed,8.8,95,92
...,...,...,...,...,...,...,...,...,...
984,984,female,group C,some high school,standard,none,7.4,75,82
987,987,male,group E,some high school,standard,completed,8.1,75,76
990,990,male,group E,high school,free/reduced,completed,8.6,81,75
995,995,female,group E,master's degree,standard,completed,8.8,99,95
999,999,female,group D,some college,free/reduced,none,7.7,86,86

In [58]:
# Traer solo las filas donde reading score sea menor a 60
readingScore_mask = students_df['reading score'] > 60 # Esta es la mascara booleana
students_df[readingScore_mask] # Filtramos los datos que cumplen las condicion

,Unnamed: 0,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,7.2,72,74
1,1,female,group C,some college,standard,completed,6.9,90,88
2,2,female,group B,master's degree,standard,none,9.0,95,93
4,4,male,group C,some college,standard,none,7.6,78,75
5,5,female,group B,associate's degree,standard,none,7.1,83,78
...,...,...,...,...,...,...,...,...,...
994,994,male,group A,high school,standard,none,6.3,63,62
995,995,female,group E,master's degree,standard,completed,8.8,99,95
997,997,female,group C,high school,free/reduced,completed,5.9,71,65
998,998,female,group D,some college,standard,completed,6.8,78,77
999,999,female,group D,some college,free/reduced,none,7.7,86,86

In [59]:
# Traer solo las filas donde gender sea igual a female
gender_mask = students_df['gender'] == 'female'  # Esta es la mascara booleana
students_df[gender_mask] # Filtramos los datos que cumplen las condicion

,Unnamed: 0,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,7.2,72,74
1,1,female,group C,some college,standard,completed,6.9,90,88
2,2,female,group B,master's degree,standard,none,9.0,95,93
5,5,female,group B,associate's degree,standard,none,7.1,83,78
6,6,female,group B,some college,standard,completed,8.8,95,92
...,...,...,...,...,...,...,...,...,...
993,993,female,group D,bachelor's degree,free/reduced,none,6.2,72,74
995,995,female,group E,master's degree,standard,completed,8.8,99,95
997,997,female,group C,high school,free/reduced,completed,5.9,71,65
998,998,female,group D,some college,standard,completed,6.8,78,77
999,999,female,group D,some college,free/reduced,none,7.7,86,86

In [60]:
# Traer solo aquellas filas donde lunch sea distinto a standard
lunch_mask = students_df['lunch'] != 'standard'  # Esta es la mascara booleana
students_df[lunch_mask]  # Filtramos los datos que cumplen las condicion

,Unnamed: 0,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,3,male,group A,associate's degree,free/reduced,none,4.7,57,44
7,7,male,group B,some college,free/reduced,none,4.0,43,39
8,8,male,group D,high school,free/reduced,completed,6.4,64,67
9,9,female,group B,high school,free/reduced,none,3.8,60,50
17,17,female,group B,some high school,free/reduced,none,1.8,32,28
...,...,...,...,...,...,...,...,...,...
992,992,female,group D,associate's degree,free/reduced,none,5.5,76,76
993,993,female,group D,bachelor's degree,free/reduced,none,6.2,72,74
996,996,male,group C,high school,free/reduced,none,6.2,55,55
997,997,female,group C,high school,free/reduced,completed,5.9,71,65
999,999,female,group D,some college,free/reduced,none,7.7,86,86

In [64]:
# Traer aquellos estudiantes que posean reading and writing score mayor a 70

mask = (students_df['reading score'] > 70) & (students_df['writing score'] > 70)
students_df[mask]

,Unnamed: 0,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,7.2,72,74
1,1,female,group C,some college,standard,completed,6.9,90,88
2,2,female,group B,master's degree,standard,none,9.0,95,93
4,4,male,group C,some college,standard,none,7.6,78,75
5,5,female,group B,associate's degree,standard,none,7.1,83,78
...,...,...,...,...,...,...,...,...,...
992,992,female,group D,associate's degree,free/reduced,none,5.5,76,76
993,993,female,group D,bachelor's degree,free/reduced,none,6.2,72,74
995,995,female,group E,master's degree,standard,completed,8.8,99,95
998,998,female,group D,some college,standard,completed,6.8,78,77
999,999,female,group D,some college,free/reduced,none,7.7,86,86

In [ ]:
#Muestra los valores de writing score para aquellos estudiantes que tengan reading score mayor a math score

## DATOS FALTANTES

In [67]:
"""Los valores faltantes estan codificados normalMemente como `NaN`. 
Esto no es un string, sino que es un valor especial de `NumPy` que es tratado como un flotante."""

# isnull() -> Chequear si tenemos valores faltantes.
students_df.isnull()

,Unnamed: 0,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False

In [ ]:
# Nos entrega una suma de la cantidad de valores faltantes por columna
# Si los hay, podemos usar dropna() para eliminarlos.
students_df.isnull().sum()

Unnamed: 0                     0
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [69]:
# df.describe() --> Entrega detalles estadisticos de cada columna del DataFrame

students_df.describe()

        Unnamed: 0   math score  reading score  writing score
count  1000.000000  1000.000000    1000.000000    1000.000000
mean    499.500000     6.608900      69.169000      68.054000
std     288.819436     1.516308      14.600192      15.195657
min       0.000000     0.000000      17.000000      10.000000
25%     249.750000     5.700000      59.000000      57.750000
50%     499.500000     6.600000      70.000000      69.000000
75%     749.250000     7.700000      79.000000      79.000000
max     999.000000    10.000000     100.000000     100.000000

In [ ]:
# Tambien es posible calcular el promedio, maximo, minimo sobre cada columna.

students_df['math score'].mean() #Calcula el promedio de la columna math score de students

np.float64(6.608899999999999)